version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/addon/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docs/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/test-app/"
    schedule:
      interval: "weekly"
